### PR TITLE
Fix: Preserve code block / edit post carriage return

### PR DESCRIPTION
**Pull request by ericlindstrom**

### CODE REVIEW

**Comment by cham** [comment]
looks fine, could you squash 3d265b8 up into 4a6c200 ? Thanks! :+1:

**Comment by cham** [comment]
if you've done squashed stuff up before then let me know - I have no idea what your git-foo is like :)

**Comment by ericlindstrom** [comment]
hopefully that worked!

**Comment by cham** [comment]
it'll probably bring in the earlier commits and the new one but I can sort that out and force push the new hashes, will merge later this evening when I have some time to work on yay again!

**Comment by cham** [comment]
fwiw a rebase would be preferable to merging to avoid the merge commits, and you can squash down with an interactive rebase, but it nabd

**Comment by ericlindstrom** [comment]
Ok, so is this good to go?

**Comment by cham** [comment]
yep! Was just having a week off yay code as I had a talk to give that week. MERGED!

**Comment by cham** [comment]
deployed, looks good from here :)

**Comment by ericlindstrom** [comment]
Thanks!

**Pull request merged**
